version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 server.py"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    restart: on-failure
