---
- name: Update package cache
  apt:
    update_cache: yes

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - unzip
    - python3-pip
    - python3-docker
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
