- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present 

- name: Install Docker
  apt:
    name: docker-ce={{ docker_version }}
    state: present
    update_cache: true

- name: Start Docker service
  service:
    name: docker
    state: started
