---
- name: Provision Web Application Host
  hosts: webapp
  become: yes
  gather_facts: yes
  vars_files: 
    - vars/main.yml

  roles:
    - common
    - nginx
    - docker
    - redis
    - postgresql
