---
- name: Add PostgreSQL GPG apt Key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL Repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name: postgresql-{{ postgres_version }}
    state: present

- name: Configure PostgreSQL
  template:
    src: postgres.conf.j2
    dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: "0640"
  notify: restart postgresql

- name: Configure PostgreSQL
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: "0640"
  notify: restart postgresql